# main text of home
name: Wallison Alves
bio: Agropecuário apaixonado por tudo que envolve tecnologia!

# twitter summary info
description: Um blog sobre agricultura, pecuária, tecnologia e assuntos relacionados

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.png

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: true
resume-url: https://google.com/?q=Wallison+Alves

url: https://wallisonalves.com
# your url: http://wallisonalves.github.io

permalink: /:title/

# if you don't have any of social below, comment the line
gpg: key.asc
tox: wallisonalvesdeoliveira
email: wallisonalvesdeoliveira@zoho.com
gitlab: wallisonalves
github: wallisonalves
keybase: wallisonalves
mastodon: wallisonalves
matrix: alveswallison:matrix.cryptodont.io
telegram: wallisonalves
twitter: wall_is_on

authors:
    wallisonalves:
        name: Wallison Alves
        bio: Agropecuário apaixonado por tudo que envolve tecnologia!
        external-image: false
        picture: assets/images/profile.png

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com
